/* Shared language selector for every farm screen. The choice is saved on this device. */
const FARM_LANGUAGES = {
  en:{name:"English",native:"English",t:{fleet:"Fleet",weather:"Weather & Alerts",market:"Market Details",support:"Farm Support",finance:"Farm Finance",growth:"Plant Growth",weather_title:"Farm weather, made actionable.",weather_intro:"Live conditions and farm-ready warnings for irrigation, spraying and crop protection.",live_weather:"LIVE FIELD WEATHER",expected_rain:"EXPECTED RAIN",farm_alerts:"FARM ALERTS",action_required:"Action when it matters"}},
  hi:{name:"Hindi",native:"हिन्दी",t:{fleet:"डैशबोर्ड",weather:"मौसम व अलर्ट",market:"बाज़ार विवरण",support:"कृषि सहायता",finance:"कृषि वित्त",growth:"पौध वृद्धि",weather_title:"खेत का मौसम, उपयोगी सलाह के साथ।",weather_intro:"सिंचाई, छिड़काव और फसल सुरक्षा के लिए लाइव मौसम और चेतावनियां।",live_weather:"लाइव खेत मौसम",expected_rain:"अनुमानित वर्षा",farm_alerts:"कृषि चेतावनियां",action_required:"सही समय पर कार्य"}},
  bn:{name:"Bengali",native:"বাংলা",t:{fleet:"ড্যাশবোর্ড",weather:"আবহাওয়া ও সতর্কতা",market:"বাজারের তথ্য",support:"কৃষি সহায়তা",finance:"কৃষি অর্থায়ন",growth:"গাছের বৃদ্ধি",weather_title:"খামারের আবহাওয়া, কাজের পরামর্শসহ।",weather_intro:"সেচ, স্প্রে ও ফসল সুরক্ষার জন্য লাইভ আবহাওয়া।",live_weather:"লাইভ খামার আবহাওয়া",expected_rain:"প্রত্যাশিত বৃষ্টি",farm_alerts:"খামার সতর্কতা",action_required:"সময়ে ব্যবস্থা নিন"}},
  mr:{name:"Marathi",native:"मराठी",t:{fleet:"डॅशबोर्ड",weather:"हवामान व सूचना",market:"बाजार तपशील",support:"शेती मदत",finance:"शेती वित्त",growth:"वनस्पती वाढ",weather_title:"शेतातील हवामान, कृतीयोग्य माहितीसह.",weather_intro:"सिंचन, फवारणी आणि पीक संरक्षणासाठी थेट हवामान.",live_weather:"थेट शेत हवामान",expected_rain:"अपेक्षित पाऊस",farm_alerts:"शेती सूचना",action_required:"योग्य वेळी कृती"}},
  gu:{name:"Gujarati",native:"ગુજરાતી",t:{fleet:"ડેશબોર્ડ",weather:"હવામાન અને ચેતવણીઓ",market:"બજાર વિગતો",support:"ખેતી સહાય",finance:"ખેતી ધિરાણ",growth:"છોડની વૃદ્ધિ",weather_title:"ખેતરનું હવામાન, ઉપયોગી સલાહ સાથે.",weather_intro:"સિંચાઈ, છંટકાવ અને પાક સુરક્ષા માટે જીવંત હવામાન.",live_weather:"લાઇવ ખેતર હવામાન",expected_rain:"અપેક્ષિત વરસાદ",farm_alerts:"ખેતી ચેતવણીઓ",action_required:"સમયસર પગલાં"}},
  ta:{name:"Tamil",native:"தமிழ்",t:{fleet:"முகப்பு",weather:"வானிலை மற்றும் எச்சரிக்கை",market:"சந்தை விவரங்கள்",support:"பண்ணை உதவி",finance:"பண்ணை நிதி",growth:"தாவர வளர்ச்சி",weather_title:"செயல்பட உதவும் பண்ணை வானிலை.",weather_intro:"நீர்ப்பாசனம், தெளித்தல் மற்றும் பயிர் பாதுகாப்பிற்கான நேரடி வானிலை.",live_weather:"நேரடி பண்ணை வானிலை",expected_rain:"எதிர்பார்க்கும் மழை",farm_alerts:"பண்ணை எச்சரிக்கைகள்",action_required:"சரியான நேரத்தில் செயல்"}},
  te:{name:"Telugu",native:"తెలుగు",t:{fleet:"డాష్‌బోర్డ్",weather:"వాతావరణం మరియు హెచ్చరికలు",market:"మార్కెట్ వివరాలు",support:"వ్యవసాయ సహాయం",finance:"వ్యవసాయ ఆర్థికం",growth:"మొక్క పెరుగుదల",weather_title:"చర్యలకు తోడ్పడే వ్యవసాయ వాతావరణం.",weather_intro:"నీటిపారుదల, పిచికారీ మరియు పంట రక్షణ కోసం ప్రత్యక్ష వాతావరణం.",live_weather:"ప్రత్యక్ష పొలం వాతావరణం",expected_rain:"అంచనా వర్షం",farm_alerts:"పొలం హెచ్చరికలు",action_required:"సమయానుకూల చర్య"}},
  kn:{name:"Kannada",native:"ಕನ್ನಡ",t:{fleet:"ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",weather:"ಹವಾಮಾನ ಮತ್ತು ಎಚ್ಚರಿಕೆ",market:"ಮಾರುಕಟ್ಟೆ ವಿವರ",support:"ಕೃಷಿ ನೆರವು",finance:"ಕೃಷಿ ಹಣಕಾಸು",growth:"ಸಸ್ಯ ಬೆಳವಣಿಗೆ",weather_title:"ಕ್ರಮಕ್ಕೆ ನೆರವಾಗುವ ಕೃಷಿ ಹವಾಮಾನ.",weather_intro:"ನೀರಾವರಿ, ಸಿಂಪಡಣೆ ಮತ್ತು ಬೆಳೆ ರಕ್ಷಣೆಗಾಗಿ ನೇರ ಹವಾಮಾನ.",live_weather:"ನೇರ ಕೃಷಿ ಹವಾಮಾನ",expected_rain:"ನಿರೀಕ್ಷಿತ ಮಳೆ",farm_alerts:"ಕೃಷಿ ಎಚ್ಚರಿಕೆಗಳು",action_required:"ಸರಿಯಾದ ಸಮಯದಲ್ಲಿ ಕ್ರಮ"}},
  ml:{name:"Malayalam",native:"മലയാളം",t:{fleet:"ഡാഷ്ബോർഡ്",weather:"കാലാവസ്ഥയും മുന്നറിയിപ്പുകളും",market:"വിപണി വിവരങ്ങൾ",support:"കൃഷി സഹായം",finance:"കൃഷി ധനസഹായം",growth:"ചെടി വളർച്ച",weather_title:"പ്രവർത്തനത്തിന് സഹായിക്കുന്ന കൃഷി കാലാവസ്ഥ.",weather_intro:"ജലസേചനം, തളിക്കൽ, വിള സംരക്ഷണം എന്നിവയ്ക്കുള്ള തത്സമയ കാലാവസ്ഥ.",live_weather:"തത്സമയ കൃഷി കാലാവസ്ഥ",expected_rain:"പ്രതീക്ഷിക്കുന്ന മഴ",farm_alerts:"കൃഷി മുന്നറിയിപ്പുകൾ",action_required:"സമയബന്ധിത നടപടി"}},
  pa:{name:"Punjabi",native:"ਪੰਜਾਬੀ",t:{fleet:"ਡੈਸ਼ਬੋਰਡ",weather:"ਮੌਸਮ ਅਤੇ ਚੇਤਾਵਨੀਆਂ",market:"ਮੰਡੀ ਵੇਰਵੇ",support:"ਖੇਤੀ ਸਹਾਇਤਾ",finance:"ਖੇਤੀ ਵਿੱਤ",growth:"ਪੌਦੇ ਦੀ ਵਾਧਾ",weather_title:"ਕੰਮਯੋਗ ਸਲਾਹ ਨਾਲ ਖੇਤ ਦਾ ਮੌਸਮ।",weather_intro:"ਸਿੰਚਾਈ, ਛਿੜਕਾਅ ਅਤੇ ਫਸਲ ਸੁਰੱਖਿਆ ਲਈ ਲਾਈਵ ਮੌਸਮ।",live_weather:"ਲਾਈਵ ਖੇਤ ਮੌਸਮ",expected_rain:"ਅਨੁਮਾਨਿਤ ਮੀਂਹ",farm_alerts:"ਖੇਤੀ ਚੇਤਾਵਨੀਆਂ",action_required:"ਸਹੀ ਸਮੇਂ ਕਾਰਵਾਈ"}},
  or:{name:"Odia",native:"ଓଡ଼ିଆ",t:{fleet:"ଡ୍ୟାସବୋର୍ଡ",weather:"ପାଣିପାଗ ଓ ସତର୍କତା",market:"ବଜାର ବିବରଣୀ",support:"କୃଷି ସହାୟତା",finance:"କୃଷି ଅର୍ଥ",growth:"ଗଛ ବୃଦ୍ଧି",weather_title:"କାମରେ ଉପଯୋଗୀ କୃଷି ପାଣିପାଗ।",weather_intro:"ଜଳସେଚନ, ସ୍ପ୍ରେ ଓ ଫସଲ ସୁରକ୍ଷା ପାଇଁ ସିଧା ପାଣିପାଗ।",live_weather:"ସିଧା କ୍ଷେତ ପାଣିପାଗ",expected_rain:"ଆଶା କରାଯାଉଥିବା ବର୍ଷା",farm_alerts:"କୃଷି ସତର୍କତା",action_required:"ଠିକ ସମୟରେ କାର୍ଯ୍ୟ"}},
  as:{name:"Assamese",native:"অসমীয়া",t:{fleet:"ডেশ্বব'ৰ্ড",weather:"বতৰ আৰু সতৰ্কতা",market:"বজাৰৰ বিৱৰণ",support:"কৃষি সহায়",finance:"কৃষি বিত্ত",growth:"গছৰ বৃদ্ধি",weather_title:"কামত সহায়ক খেতিৰ বতৰ।",weather_intro:"সিঞ্চন, স্প্ৰে আৰু শস্য সুৰক্ষাৰ বাবে লাইভ বতৰ।",live_weather:"লাইভ খেতিৰ বতৰ",expected_rain:"প্ৰত্যাশিত বৰষুণ",farm_alerts:"খেতি সতৰ্কতা",action_required:"সময়মতে ব্যৱস্থা"}},
  ur:{name:"Urdu",native:"اردو",t:{fleet:"ڈیش بورڈ",weather:"موسم اور انتباہ",market:"مارکیٹ تفصیل",support:"فارم مدد",finance:"فارم فنانس",growth:"پودے کی نشوونما",weather_title:"عملی رہنمائی کے ساتھ فارم کا موسم۔",weather_intro:"آبپاشی، اسپرے اور فصل کے تحفظ کے لیے براہ راست موسم۔",live_weather:"لائیو فارم موسم",expected_rain:"متوقع بارش",farm_alerts:"فارم انتباہ",action_required:"بروقت کارروائی"}}
};
const farmOriginalText = new WeakMap(); let translationRun = 0;
function visibleTextNodes(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement;if(!p||["SCRIPT","STYLE","OPTION","TEXTAREA"].includes(p.tagName)||p.closest(".farm-language, .top-tabs, [data-i18n]"))return NodeFilter.FILTER_REJECT;const v=n.nodeValue.trim();return v.length>2&&/[A-Za-z]/.test(v)&&!/^[-+]?\d+(\.\d+)?$/.test(v)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;}});const result=[];while(walker.nextNode())result.push(walker.currentNode);return result;}
async function translateBatch(texts,target){const source=texts.join("\n");const key=`farm_translate_${target}_${source}`;const cached=localStorage.getItem(key);if(cached)return cached.split("\n");try{const url="https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl="+encodeURIComponent(target)+"&dt=t&q="+encodeURIComponent(source);const json=await fetch(url).then(r=>{if(!r.ok)throw Error("translation unavailable");return r.json();});const translated=json[0].map(part=>part[0]).join("");localStorage.setItem(key,translated);return translated.split("\n");}catch(e){return texts;}}
async function translateWholePage(code){const run=++translationRun;const nodes=visibleTextNodes();const phrases=nodes.map(n=>{if(!farmOriginalText.has(n))farmOriginalText.set(n,n.nodeValue);else n.nodeValue=farmOriginalText.get(n);return farmOriginalText.get(n).trim();});const attributes=[];document.querySelectorAll("[placeholder],[title]").forEach(node=>{for(const attr of ["placeholder","title"]){const original=`data-farm-original-${attr}`;if(!node.hasAttribute(original))node.setAttribute(original,node.getAttribute(attr)||"");const value=node.getAttribute(original);if(value)node.setAttribute(attr,value);if(value&&/[A-Za-z]/.test(value))attributes.push([node,attr,value]);}});if(code==="en")return;for(let i=0;i<nodes.length;i+=20){const chunk=phrases.slice(i,i+20);const translated=await translateBatch(chunk,code);if(run!==translationRun)return;translated.forEach((value,index)=>{if(value)nodes[i+index].nodeValue=nodes[i+index].nodeValue.replace(phrases[i+index],value);});}attributes.forEach(async ([node,attr,value])=>{const [translated]=await translateBatch([value],code);if(run===translationRun&&translated)node.setAttribute(attr,translated);});}
function translateFarmPage(code){const lang=FARM_LANGUAGES[code]||FARM_LANGUAGES.en;localStorage.setItem("farm_language",code);document.documentElement.lang=code;document.documentElement.dir=code==="ur"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(node=>{const value=lang.t[node.dataset.i18n];if(value)node.textContent=value;});document.querySelectorAll(".top-tabs .tab").forEach(a=>{const href=a.getAttribute("href")||"";const key=href.includes("index")?"fleet":href.includes("weather")?"weather":href.includes("market")?"market":href.includes("support")?"support":href.includes("finance")?"finance":href.includes("plant")?"growth":null;if(key&&lang.t[key])a.textContent=lang.t[key];});const s=document.getElementById("farmLanguage");if(s)s.value=code;translateWholePage(code);}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".top-tabs").forEach(nav=>{if(!nav.querySelector('[href="weather.html"]'))nav.insertAdjacentHTML("beforeend",'<a href="weather.html" class="tab">Weather & Alerts</a>');if(!nav.querySelector('[href="finance.html"]'))nav.insertAdjacentHTML("beforeend",'<a href="finance.html" class="tab">Farm Finance</a>');});const host=document.querySelector(".topnav-right");if(host&&!document.getElementById("farmLanguage")){const select=document.createElement("select");select.id="farmLanguage";select.className="farm-language";select.setAttribute("aria-label","Choose language");select.innerHTML=Object.entries(FARM_LANGUAGES).map(([id,x])=>`<option value="${id}">${x.native} — ${x.name}</option>`).join("");select.onchange=e=>translateFarmPage(e.target.value);host.prepend(select);}translateFarmPage(localStorage.getItem("farm_language")||"en");});
