const WEATHER_ENDPOINT = "https://api.open-meteo.com/v1/forecast";
let weatherCoords = { lat: 30.9010, lon: 75.8573, label: "Ludhiana, Punjab (default)" };
const weatherCode = {0:["Clear sky","☀"],1:["Mostly clear","🌤"],2:["Partly cloudy","⛅"],3:["Overcast","☁"],45:["Fog","🌫"],48:["Rime fog","🌫"],51:["Light drizzle","🌦"],53:["Drizzle","🌦"],55:["Heavy drizzle","🌧"],61:["Light rain","🌦"],63:["Rain","🌧"],65:["Heavy rain","🌧"],71:["Light snow","🌨"],73:["Snow","🌨"],75:["Heavy snow","❄"],80:["Rain showers","🌦"],81:["Rain showers","🌧"],82:["Heavy showers","⛈"],95:["Thunderstorm","⛈"],96:["Thunderstorm with hail","⛈"],99:["Severe thunderstorm","⛈"]};
const el = id => document.getElementById(id);
function fmtDate(date, i){ if(i===0) return "Today"; if(i===1) return "Tomorrow"; return new Date(date+"T12:00:00").toLocaleDateString(undefined,{weekday:"short"}); }
function getAlerts(d){const c=d.current, day=d.daily, alerts=[]; const rain24=day.precipitation_sum[0], rain2=day.precipitation_sum.slice(0,2).reduce((a,b)=>a+b,0); if(c.weather_code>=95)alerts.push(["high","Thunderstorm risk","Avoid open-field work and keep workers, livestock and equipment under shelter."]); else if(rain2>=25)alerts.push(["high","Heavy rain expected","Clear drainage channels now. Pause irrigation and postpone fertilizer or pesticide application."]); else if(rain24>=4)alerts.push(["medium","Rain expected","Do not irrigate until after the rain. Keep harvested produce covered."]); if(c.wind_speed_10m>=30)alerts.push(["high","Strong wind","Delay pesticide spraying and secure trellis, shade net and young plants."]); else if(c.wind_speed_10m>=20)alerts.push(["medium","Spray drift risk","Only spray in calm periods; wind can carry chemicals off-target."]); if(c.temperature_2m>=38)alerts.push(["high","Heat stress","Irrigate early morning, mulch exposed soil and check seedlings for wilting."]); else if(c.temperature_2m<=5)alerts.push(["high","Cold stress","Protect sensitive crops with cover and avoid evening irrigation."]); if(c.relative_humidity_2m>=85 && c.temperature_2m>=18)alerts.push(["medium","Fungal disease conditions","Inspect leaves and improve airflow. Avoid overhead watering this evening."]); if(!alerts.length)alerts.push(["low","Field window looks favourable","Conditions are suitable for routine scouting and planned work. Keep monitoring rainfall before irrigation."]); return alerts;}
function render(d){const c=d.current, day=d.daily, info=weatherCode[c.weather_code]||["Unknown","⛅"];el("temperature").textContent=Math.round(c.temperature_2m);el("apparent").textContent=Math.round(c.apparent_temperature)+"°C";el("humidity").textContent=Math.round(c.relative_humidity_2m)+"%";el("wind").textContent=Math.round(c.wind_speed_10m)+" km/h";el("condition").textContent=info[0];el("weatherSymbol").textContent=info[1];el("rainToday").textContent=`${Number(day.precipitation_sum[0]).toFixed(1)} mm today`;el("rainNext").textContent=`${day.precipitation_sum.reduce((a,b)=>a+b,0).toFixed(1)} mm in next 7 days`;const alerts=getAlerts(d);el("alertCount").textContent=`${alerts.length} active`;el("alertsList").innerHTML=alerts.map(a=>`<div class="alert ${a[0]}"><div class="alert-head">${a[1]}</div><p>${a[2]}</p></div>`).join("");el("forecast").innerHTML=day.time.map((date,i)=>{const w=weatherCode[day.weather_code[i]]||["Mixed","⛅"];return `<div class="forecast-day"><b>${fmtDate(date,i)}</b><span>${w[1]}</span><span class="forecast-temp">${Math.round(day.temperature_2m_min[i])}° – ${Math.round(day.temperature_2m_max[i])}°</span><span class="rain-amount">☔ ${Number(day.precipitation_sum[i]).toFixed(1)} mm</span></div>`}).join("");const top=alerts[0];el("advisoryTitle").textContent=top[1];el("advisoryText").textContent=top[2];el("lastUpdated").textContent="Last updated " + new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});el("weatherStatus").textContent="Live from Open‑Meteo";}
async function loadWeather(){el("weatherStatus").textContent="Refreshing…"; try{const u=new URL(WEATHER_ENDPOINT);Object.entries({latitude:weatherCoords.lat,longitude:weatherCoords.lon,current:"temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m",daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max",timezone:"auto",forecast_days:7}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);if(!r.ok)throw Error();render(await r.json());}catch(e){el("weatherStatus").textContent="Unable to reach Open‑Meteo — retry";el("condition").textContent="Weather connection unavailable";}}
function locate(){if(!navigator.geolocation){loadWeather();return;}el("locationName").textContent="Requesting farm location…";navigator.geolocation.getCurrentPosition(p=>{weatherCoords={lat:p.coords.latitude,lon:p.coords.longitude,label:`Your farm: ${p.coords.latitude.toFixed(4)}°, ${p.coords.longitude.toFixed(4)}°`};el("locationName").textContent=weatherCoords.label;loadWeather();},()=>{el("locationName").textContent=weatherCoords.label;loadWeather();},{enableHighAccuracy:true,timeout:8000,maximumAge:300000});}
document.addEventListener("DOMContentLoaded",()=>{el("refreshBtn").onclick=loadWeather;el("locationBtn").onclick=locate;locate();});
